const sites = [
  {
    name: 'changfu',
    baseUrl: 'https://www.changfu.me',
    sitemapUrl: 'https://www.changfu.me/sitemap.xml',
    indexingApiPaths: [],
    pages: [
      '/',
      '/about.html',
      '/services.html',
      '/news.html',
      '/courses.html',
      '/jobs.html',
      '/contact.html',
    ],
    keywords: [
      '宜蘭長照',
      '宜蘭長期照護',
      '長照協會 宜蘭',
      '冬山日照中心',
      '失智據點 宜蘭',
      '樂智據點 宜蘭',
      '輔具資源 宜蘭',
      '宜蘭縣長期照護協會',
      '長照服務 冬山',
      '宜蘭社會福祉',
      'changfu.me',
    ],
  },
  {
    name: 'kingkitchen',
    baseUrl: 'https://kingkitchen.changfu.me',
    sitemapUrl: 'https://kingkitchen.changfu.me/sitemap.xml',
    indexingApiPaths: [],
    pages: [
      '/',
      '/about',
      '/services',
      '/services/kitchen',
      '/services/ventilation',
      '/services/hvac',
      '/services/drainage',
      '/process',
      '/projects',
      '/contact',
    ],
    keywords: [
      '宜蘭廚房設備',
      '商業廚房工程',
      '排煙工程 宜蘭',
      '不鏽鋼廚房設備',
      '皇廚企業社',
      '蘇澳廚房設備',
      '油水分離槽',
      '商業廚房設備安裝',
      '宜蘭排煙系統',
      '廚房冷氣風管 宜蘭',
      'kingkitchen.changfu.me',
    ],
  },
];

module.exports = { sites };
